import type {
  UserProfile,
  Course,
  Quest,
  Achievement,
} from './types';

export const user: UserProfile = {
  name: 'Maya Chen',
  title: 'Product Engineer · Level 12',
  level: 12,
  totalXp: 8470,
  xpToNextLevel: 1000,
  xpInLevel: 620,
  streak: 23,
  streakBest: 41,
  rank: 'Journeyman',
  rankPercentile: 8,
  weeklyGoalMinutes: 180,
  weeklyMinutesCompleted: 135,
  skills: [
    { name: 'System Design', level: 4, xp: 780, nextLevelXp: 1000, category: 'Engineering' },
    { name: 'SQL Modeling', level: 3, xp: 540, nextLevelXp: 800, category: 'Data' },
    { name: 'UX Writing', level: 2, xp: 320, nextLevelXp: 500, category: 'Communication' },
    { name: 'Strategic Framing', level: 3, xp: 610, nextLevelXp: 800, category: 'Strategy' },
  ],
};

export const continueCourse: Course = {
  id: 'sys-design-arch',
  title: 'System Design for Builders',
  subtitle: 'From single-server sketches to distributed architectures',
  category: 'Engineering',
  level: 'Advanced',
  instructor: 'Dr. Arjun Patel',
  instructorTitle: 'Staff Engineer, ex-Stripe',
  totalLessons: 18,
  completedLessons: 11,
  totalMinutes: 320,
  xpReward: 450,
  skills: ['Load Balancing', 'Caching', 'Sharding', 'CAP Theory'],
  coverAccent: 'blueprint',
  isContinue: true,
  lessons: [
    { id: 'l9', title: 'Read Replicas vs. Caching', durationMin: 18, completed: true },
    { id: 'l10', title: 'Sharding Strategies', durationMin: 22, completed: true },
    { id: 'l11', title: 'Eventual Consistency Patterns', durationMin: 16, completed: true },
    { id: 'l12', title: 'The CAP Theorem in Practice', durationMin: 24, completed: false, current: true },
    { id: 'l13', title: 'Distributed Locks & Quorums', durationMin: 20, completed: false },
    { id: 'l14', title: 'Design Review: URL Shortener', durationMin: 28, completed: false },
  ],
};

export const courses: Course[] = [
  {
    id: 'sql-mastery',
    title: 'SQL Modeling Mastery',
    subtitle: 'Design schemas that scale from prototype to production',
    category: 'Data',
    level: 'Intermediate',
    instructor: 'Lena Volkov',
    instructorTitle: 'Data Lead, ex-Notion',
    totalLessons: 14,
    completedLessons: 6,
    totalMinutes: 210,
    xpReward: 320,
    skills: ['Normalization', 'Indexes', 'Window Functions'],
    coverAccent: 'brass',
    lessons: [],
  },
  {
    id: 'strategic-framing',
    title: 'Strategic Framing & Prioritization',
    subtitle: 'Cut noise, frame decisions, communicate tradeoffs',
    category: 'Strategy',
    level: 'Foundations',
    instructor: 'Marcus Reid',
    instructorTitle: 'Head of Product, ex-Figma',
    totalLessons: 10,
    completedLessons: 3,
    totalMinutes: 150,
    xpReward: 240,
    skills: ['RICE', 'Opportunity Scoring', 'JTBD'],
    coverAccent: 'signal',
    lessons: [],
  },
  {
    id: 'ux-writing',
    title: 'UX Writing for Interfaces',
    subtitle: 'Microcopy that guides, calms, and converts',
    category: 'Communication',
    level: 'Foundations',
    instructor: 'Sofia Almeida',
    instructorTitle: 'Sr. Content Designer, ex-Airbnb',
    totalLessons: 12,
    completedLessons: 8,
    totalMinutes: 180,
    xpReward: 280,
    skills: ['Voice & Tone', 'Error Messages', 'Onboarding'],
    coverAccent: 'moss',
    lessons: [],
  },
  {
    id: 'advanced-caching',
    title: 'Advanced Caching Architecture',
    subtitle: 'Cache hierarchies, invalidation, and edge strategies',
    category: 'Engineering',
    level: 'Expert',
    instructor: 'Dr. Arjun Patel',
    instructorTitle: 'Staff Engineer, ex-Stripe',
    totalLessons: 16,
    completedLessons: 0,
    totalMinutes: 280,
    xpReward: 500,
    skills: ['Redis', 'CDN', 'Invalidation', 'Cache Stampede'],
    coverAccent: 'blueprint',
    lessons: [],
  },
  {
    id: 'design-systems',
    title: 'Design Systems at Scale',
    subtitle: 'Build token-driven systems teams actually adopt',
    category: 'Design',
    level: 'Advanced',
    instructor: 'Yuki Tanaka',
    instructorTitle: 'Design Systems Lead, ex-Shopify',
    totalLessons: 15,
    completedLessons: 2,
    totalMinutes: 240,
    xpReward: 380,
    skills: ['Tokens', 'Component API', 'Governance'],
    coverAccent: 'brass',
    lessons: [],
  },
  {
    id: 'data-viz',
    title: 'Data Visualization Craft',
    subtitle: 'Charts that reveal rather than decorate',
    category: 'Data',
    level: 'Intermediate',
    instructor: 'Yuki Tanaka',
    instructorTitle: 'Design Systems Lead, ex-Shopify',
    totalLessons: 13,
    completedLessons: 0,
    totalMinutes: 195,
    xpReward: 300,
    skills: ['Chart Types', 'Perception', 'Annotation'],
    coverAccent: 'signal',
    lessons: [],
  },
];

export const quests: Quest[] = [
  {
    id: 'q1',
    title: 'Complete 2 lessons',
    description: 'Keep the momentum going',
    xp: 80,
    progress: 1,
    target: 2,
    icon: 'target',
  },
  {
    id: 'q2',
    title: 'Maintain your streak',
    description: 'Study today to extend to 24',
    xp: 50,
    progress: 23,
    target: 24,
    icon: 'flame',
  },
  {
    id: 'q3',
    title: 'Earn 200 XP this week',
    description: 'You\'re over halfway there',
    xp: 150,
    progress: 135,
    target: 200,
    icon: 'zap',
  },
  {
    id: 'q4',
    title: 'Finish a skill module',
    description: 'Complete all lessons in one module',
    xp: 120,
    progress: 0,
    target: 1,
    icon: 'brain',
  },
];

export const achievements: Achievement[] = [
  { id: 'a1', name: 'First Spark', description: 'Complete your first lesson', icon: 'zap', unlocked: true, date: 'Jun 12', rarity: 'common' },
  { id: 'a2', name: 'Week One', description: '7-day streak', icon: 'flame', unlocked: true, date: 'Jun 18', rarity: 'common' },
  { id: 'a3', name: 'Deep Diver', description: 'Complete an Expert course', icon: 'medal', unlocked: true, date: 'Jul 03', rarity: 'rare' },
  { id: 'a4', name: 'Polymath', description: 'Study 3 different categories', icon: 'award', unlocked: true, date: 'Jul 20', rarity: 'rare' },
  { id: 'a5', name: 'Iron Will', description: '30-day streak', icon: 'trophy', unlocked: false, rarity: 'epic' },
  { id: 'a6', name: 'Master Builder', description: 'Reach Level 20', icon: 'star', unlocked: false, rarity: 'legendary' },
];
